apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: {{.SampleAppName}}-subscription
  namespace: default
spec:
  channel: default/{{.SampleAppName}}-helmrepo
  name: nginx-ingress
  placement:
    placementRef:
      name: {{.SampleAppName}}-placement
      kind: Placement
  packageOverrides:
  - packageName: nginx-lego
    packageAlias: nginx-lego-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 2
